### ISSUE TITLE
add loss or R2

### ISSUE THREAD

**Issue by triwahyuu** [reshalfahsi/regression#3]
we could calculate R2 easily.
see https://en.wikipedia.org/wiki/Coefficient_of_determination

**Comment by reshalfahsi** [comment]
quite possibly for future update and little help, perhaps?

**Comment by triwahyuu** [comment]
done in #4 @reshalfahsi

**Comment by reshalfahsi** [comment]
I'll closed this issue, mark as solved

**Comment by triwahyuu** [comment]
actually, you don't need to close the issue manually as I have linked the pull request to this issue, so it will automatically close this issue once you merged the PR
